services:
  mysql:
    image: postgres:17.6
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: polardb_order
    ports:
      - '5432:5432'
  rabbitmq:
    image: rabbitmq:4.1.4-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - '5672:5672'
      - '15672:15672'
