name: Commit Stage
on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: giwankim/order-service
  VERSION: latest

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '24'
          cache: 'gradle'
      - name: Build, unit and integration tests
        run: |
          chmod +x gradlew
          ./gradlew build --no-daemon
      - name: Code vulnerability scan
        uses: anchore/scan-action@v6
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: 'high'
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Setup tools
        uses: alexellis/setup-arkade@v3
      - name: Install tools
        uses: alexellis/arkade-get@master
        with:
          kubeconform: latest
      - name: Validate Kubernetes manifests
        run: |
          kubeconform --strict k8s
  package:
    name: Package and Publish
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ build ]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '24'
          cache: 'gradle'
